from django.core.exceptions import ValidationError
from add_member.models import Person
from add_case.models import Case
from meeting.models import Meeting

